# This compose file is meant for development purposes.
# Please use the deployment steps provided in the readme for production use.

services:
  crop-transparent:
    container_name: crop-transparent
    build: .
    ports:
      - "3784:5000"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
